# POST    http://localhost:4004/odata/v4/EmployeeSrv/budgetchecking
# Content-Type: application/json
# Authorization: Basic alice
 
# {
#     "budget": [
#       {
#       "YEAR": "2026",
#       "INTERNAL_ORDER": "1",
#       "FUND_CENTER": "112S30006", 
#       "MATERIAL_GROUP": "732002901", 
#       "COMMITMENT_ITEM": "732002",
#       "CLAIM_TYPE_ITEM": "KILOMETER",
#       "AMOUNT": 100.00, 
#       "INDICATOR": "REQ", 
#       "ACTION": "SUBMIT"
#      }
#     ]
# }


# GET http://localhost:4004/odata/v4/EmployeeSrv/getEmailReminder()
# Authorization: Basic alice



# POST    http://localhost:4004/odata/v4/EmployeeSrv/batchCreateBudget
# Content-Type: application/json
 
#    {
#     "budget": [
#         {
#             "COMMITMENT_ITEM": "760001",
#             "FUND_CENTER": "108S37004",
#             "INTERNAL_ORDER": "1",
#             "MATERIAL_GROUP": "760001959",
#             "ORIGINAL_BUDGET": "10.00",
#             "RETURN": "10.00",
#             "SUPPLEMENT": "10.00",
#             "VIREMENT_IN": "90.00",
#             "VIREMENT_OUT": "0.00",
#             "YEAR": "2026",
#             "HasActiveEntity": false,
#             "HasDraftEntity": false,
#             "IsActiveEntity": true
#         }
#     ]
# }

# POST    http://localhost:4004/odata/v4/EmployeeSrv/onFinalApproveInsert
# Content-Type: application/json
# Authorization: Basic alice
 
#    {
#     "ApproveRequest": [
#       {
#         "EMP_ID": "E1205",
#         "REQUEST_ID": "REQ26",
#         "AMOUNT": 1000.00,
#         "CLAIMED": 1
#      }
#     ]
#    }

# POST    http://localhost:4004/odata/v4/EmployeeSrv/WorkflowApproval
# Content-Type: application/json
# Authorization: Basic alice
 
#    {
#     "ClaimID": "CLM26000000001"
#    }

# POST    http://localhost:4004/odata/v4/EmployeeSrv/UpdateApproverDetails
# Content-Type: application/json
# Authorization: Basic alice
 
#    {
#     "aPayloadToCreateApproverDetailsTable": [
#      {
#         "ID"         : "CLM26000000140",
#         "LEVEL"                  : "1",
#         "APPROVER_ID"            : "903783",
#         "SUBSTITUTE_APPROVER_ID" : "902733",
#         "STATUS"                 : "STAT02",
#         "REJECT_REASON_ID"       : "R01",
#         "PROCESS_TIMESTAMP"      : "2026-03-27 01:45:57.546000000",
#         "COMMENT"                : "SEND BACk"
#      }
#     ]
#    }

   # {
   #      "ID"         : "CLM26000000140",
   #      "LEVEL"                  : "1",
   #      "APPROVER_ID"            : "903783",
   #      "SUBSTITUTE_APPROVER_ID" : "902733",
   #      "STATUS"                 : "STAT02",
   #      "REJECT_REASON_ID"       : "R01",
   #      "PROCESS_TIMESTAMP"      : "2026-03-27 01:45:57.546000000",
   #      "COMMENT"                : "SEND BACk"
   #   },
   #   {
   #      "ID"         : "CLM26000000140",
   #      "LEVEL"                  : "2",
   #      "APPROVER_ID"            : "903783",
   #      "SUBSTITUTE_APPROVER_ID" : "902733",
   #      "STATUS"                 : "STAT02",
   #      "REJECT_REASON_ID"       : "R02",
   #      "PROCESS_TIMESTAMP"      : "2026-03-27 01:45:57.546000000",
   #      "COMMENT"                : "REJECT"
   #   },
   #   {
   #      "ID"         : "CLM26000000140",
   #      "LEVEL"                  : "3",
   #      "APPROVER_ID"            : "903783",
   #      "SUBSTITUTE_APPROVER_ID" : "902733",
   #      "STATUS"                 : "STAT02",
   #      "REJECT_REASON_ID"       : "R03",
   #      "PROCESS_TIMESTAMP"      : "2026-03-27 01:45:57.546000000",
   #      "COMMENT"                : "TEST"
   #   }

   # {
   #      "ID"         : "REQ26000000022",
   #      "LEVEL"                  : "1",
   #      "APPROVER_ID"            : "1900522",
   #      "SUBSTITUTE_APPROVER_ID" : null,
   #      "STATUS"                 : "STAT02",
   #      "REJECT_REASON_ID"       : null,
   #      "PROCESS_TIMESTAMP"      : null,
   #      "COMMENT"                : null
   #   },
   #   {
   #      "ID"         : "REQ26000000022",
   #      "LEVEL"                  : "2",
   #      "APPROVER_ID"            : "1900522",
   #      "SUBSTITUTE_APPROVER_ID" : null,
   #      "STATUS"                 : "STAT02",
   #      "REJECT_REASON_ID"       : null,
   #      "PROCESS_TIMESTAMP"      : null,
   #      "COMMENT"                : null
   #   },
   #   {
   #      "ID"         : "REQ26000000022",
   #      "LEVEL"                  : "3",
   #      "APPROVER_ID"            : "1900522",
   #      "SUBSTITUTE_APPROVER_ID" : null,
   #      "STATUS"                 : "STAT02",
   #      "REJECT_REASON_ID"       : null,
   #      "PROCESS_TIMESTAMP"      : null,
   #      "COMMENT"                : null
   #   }

#    POST    http://localhost:4004/odata/v4/EmployeeSrv/DeleteApproverDetails
# Content-Type: application/json
# Authorization: Basic alice
 
#    {
#     "ID": "REQ26000000022"
#    }

POST    http://localhost:4004/odata/v4/EmployeeSrv/EligibilityCheck
Content-Type: application/json
Authorization: Basic alice
 
    {
     "aPayload": [
       {
         "CheckFields": [
            {
               "fieldName": "FARE_TYPE_ID",
               "value": "02",
               "result": null
            },
            {
               "fieldName": "ELIGIBLE_AMOUNT",
               "value": "80000",
               "result": null
            },
            {
               "fieldName": "TRANSPORT_CLASS",
               "value": "07",
               "result": null
            }
            ],
         "ClaimType": "DLM_NEGARA",
         "ClaimTypeItem": "TAMBANG",
         "EmpId": "886887",
         "RecordId": "CLM26000000874",
         "RecordSubId": "CLM26000000874001"
      }
     ]
    }


# POST http://localhost:4004/odata/v4/EmployeeSrv/getUserEligibleAmountEPengakut
# Content-Type: application/json
# Authorization: Basic alice
 
#    {
#     "sEmpId": "010320"
#    }

