POST    http://localhost:4004/odata/v4/EmployeeSrv/budgetchecking
Content-Type: application/json
 
   {
    "budget": {
      "YEAR": "2027",
      "INTERNAL_ORDER": "IO01",
      "FUND_CENTER": "00012", 
      "MATERIAL_GROUP": "0013"
    }
   }