using {ECLAIM} from '../db/eclaim';

service ECLAIM_VIEW_SRV @(requires: 'authenticated-user') {

    type ApprovedClaimItem {
        ClaimID              : String;
        ClaimSubID           : String;
        EmpID                : String;
        SubmissionDate       : String;
        FinalAmounttoReceive : Decimal(15, 2);
        LastModifiedDate     : String;
        Amount               : Decimal(15, 2);
        ReceiptDate          : String;
        CostCenter           : String;
        GLAccount            : String;
        MaterialCode         : String;
        CashAdvanceAmount    : Decimal(15, 2);
        InternalOrder        : String;
        CashAdvanceCatID     : String(10);
    }


    type ApprovedClaimBatch {
        ClaimID : String;
        Items   : many ApprovedClaimItem;
    }


    entity ZEMP_REQUEST_VIEW              as
        projection on ECLAIM.ZREQUEST_HEADER {
            key REQUEST_ID,
                EMP_ID,
                CLAIM_TYPE_ID,
                ZCLAIM_TYPE.CLAIM_TYPE_DESC,
                ZEMP_MASTER.CC              as EMPLOYEE_COST_CENTER,
                OBJECTIVE_PURPOSE,
                REQUEST_TYPE_ID,
                ZREQUEST_TYPE.REQUEST_TYPE_DESC,
                TRIP_START_DATE,
                TRIP_END_DATE,
                EVENT_START_DATE,
                EVENT_END_DATE,
                IND_OR_GROUP,
                ZINDIV_GROUP.IND_OR_GROUP_DESC,
                LOCATION,
                TYPE_OF_TRANSPORTATION,
                ALTERNATE_COST_CENTER,
                COSTCENTER.COST_CENTER_DESC as ALT_COST_CENTER_DESC,
                ATTACHMENT1,
                ATTACHMENT2,
                REMARK,
                EVENT_FIELD1,
                EVENT_FIELD2,
                EVENT_FIELD3,
                EVENT_FIELD4,
                EVENT_FIELD5,
                STATUS,
                ZSTATUS.STATUS_DESC,
                COST_CENTER,
                ZCOST_CENTER.COST_CENTER_DESC,
                CASH_ADVANCE,
                PREAPPROVAL_AMOUNT,
                TOTAL_AMOUNT,
                REQUEST_DATE,
                createdBy,
                modifiedAt,
                TRANSFER_MODE_ID,
                ZTRANSFER_MODE.TRANSFER_MODE_DESC,
                TRAVEL_ALONE_FAMILY,
                ZTRAVEL_TYPE.TRAVEL_TYPE_DESC,
                TRAVEL_FAMILY_NOW_LATER,
                ZFAMILY_TIMING.FAMILY_TIMING_DESC,
                ZEMP_MASTER.DEP,
                ZEMP_MASTER.ZDEPARTMENT.DEPARTMENT_DESC,
                ZEMP_MASTER.NAME,
                ZEMP_MASTER.POS,
                ZEMP_MASTER.POSITION_NAME,
                ZEMP_MASTER.GRADE,
                ZEMP_MASTER.JOB_GROUP,
                PAYMENT_DATE,
                PROJECT_CODE,
                ZPROJECT_HDR.PROJECT_DESC as PROJECT_DESC,
                ATTACHMENT3,
                ATTACHMENT4,
                PAYMENT_DUE_DATE
        };

    entity ZEMP_REQUEST_EE_VIEW          as
        projection on ECLAIM.ZREQUEST_HEADER {
            key REQUEST_ID,
                EMP_ID,
                CLAIM_TYPE_ID,
                ZCLAIM_TYPE.CLAIM_TYPE_DESC,
                ZEMP_MASTER.CC              as EMPLOYEE_COST_CENTER,
                OBJECTIVE_PURPOSE,
                REQUEST_TYPE_ID,
                ZREQUEST_TYPE.REQUEST_TYPE_DESC,
                TRIP_START_DATE,
                TRIP_END_DATE,
                EVENT_START_DATE,
                EVENT_END_DATE,
                IND_OR_GROUP,
                ZINDIV_GROUP.IND_OR_GROUP_DESC,
                LOCATION,
                TYPE_OF_TRANSPORTATION,
                ALTERNATE_COST_CENTER,
                COSTCENTER.COST_CENTER_DESC as ALT_COST_CENTER_DESC,
                ATTACHMENT1,
                ATTACHMENT2,
                REMARK,
                EVENT_FIELD1,
                EVENT_FIELD2,
                EVENT_FIELD3,
                EVENT_FIELD4,
                EVENT_FIELD5,
                STATUS,
                ZSTATUS.STATUS_DESC,
                COST_CENTER,
                ZCOST_CENTER.COST_CENTER_DESC,
                CASH_ADVANCE,
                PREAPPROVAL_AMOUNT,
                TOTAL_AMOUNT,
                REQUEST_DATE,
                createdBy,
                modifiedAt,
                TRANSFER_MODE_ID,
                ZTRANSFER_MODE.TRANSFER_MODE_DESC,
                TRAVEL_ALONE_FAMILY,
                ZTRAVEL_TYPE.TRAVEL_TYPE_DESC,
                TRAVEL_FAMILY_NOW_LATER,
                ZFAMILY_TIMING.FAMILY_TIMING_DESC,
                ZEMP_MASTER.DEP,
                ZEMP_MASTER.ZDEPARTMENT.DEPARTMENT_DESC,
                ZEMP_MASTER.NAME,
                ZEMP_MASTER.POS,
                ZEMP_MASTER.POSITION_NAME,
                ZEMP_MASTER.GRADE,
                ZEMP_MASTER.JOB_GROUP,
                ATTACHMENT3,
                ATTACHMENT4
        };


    entity ZEMP_REQUEST_ITEM_VIEW         as
        projection on ECLAIM.ZREQUEST_ITEM {
            key REQUEST_ID,
            key REQUEST_SUB_ID,
                CLAIM_TYPE_ID,
                ZCLAIM_TYPE.CLAIM_TYPE_DESC,
                ZCLAIM_TYPE.GL_ACCOUNT,
                CLAIM_TYPE_ITEM_ID,
                ZCLAIM_TYPE_ITEM.CLAIM_TYPE_ITEM_DESC,
                ZCLAIM_TYPE.COST_CENTER,
                COST_CENTER   as  CHARGING_COST_CENTER,
                ZCLAIM_TYPE_ITEM.MATERIAL_CODE,
                NO_OF_DAYS,
                PURPOSE,
                EST_AMOUNT,
                DEPENDENT,
                REMARK,
                COURSE_TITLE,
                KWSP_SPORTS_REPRESENTATION,
                ZSPORTS_REPRESENTATION.SPORTS_REPRESENTATION_DESC,
                DECLARE_CLUB_MEMBERSHIP,
                ATTACHMENT1,
                MOBILE_CATEGORY_PURPOSE_ID,
                ZMOBILE_CATEGORY_PURPOSE.MOBILE_CATEGORY_PURPOSE_DESC,
                ATTACHMENT2,
                START_DATE,
                END_DATE,
                VEHICLE_OWNERSHIP_ID,
                ZVEHICLE_OWNERSHIP.VEHICLE_OWNERSHIP_DESC,
                ROOM_TYPE,
                ZROOM_TYPE.ROOM_TYPE_DESC,
                COUNTRY,
                ZCOUNTRY.COUNTRY_DESC,
                LOCATION,
                AREA,
                ZAREA.AREA_DESC,
                FAMILY_COUNT,
                VEHICLE_TYPE,
                ZVEHICLE_TYPE.VEHICLE_TYPE_DESC,
                KILOMETER,
                RATE_PER_KM,
                TOLL,
                FLIGHT_CLASS,
                ZFLIGHT_CLASS.FLIGHT_CLASS_DESC,
                LOCATION_TYPE,
                ZLOC_TYPE.LOC_TYPE_DESC,
                FROM_STATE_ID,
                ZSTATE.STATE_DESC   as FROM_STATE_DESC,
                FROM_LOCATION,
                TO_STATE_ID,
                ZTOSTATE.STATE_DESC as TO_STATE_DESC,
                TO_LOCATION,
                MODE_OF_TRANSFER,
                TRANSFER_DATE,
                REGION,
                ZREGION.REGION_DESC,
                MARRIAGE_CATEGORY,
                ZMARITAL_CAT.MARRIAGE_CATEGORY_DESC,
                METER_CUBE_ENTITLED,
                METER_CUBE_ACTUAL,
                DEPARTURE_TIME,
                ARRIVAL_TIME,
                LODGING_CATEGORY,
                ZLODGING_CAT.LODGING_CATEGORY_DESC,
                EST_NO_PARTICIPANT,
                CASH_ADVANCE,
                EMP_ID,
                FROM_LOCATION_OFFICE,
                TO_LOCATION_OFFICE,
                createdBy,
                TRIP_START_DATE,
                TRIP_END_DATE,
                TRIP_START_TIME,
                TRIP_END_TIME,
                TRAVEL_DURATION_DAY,
                TRAVEL_DURATION_HOUR,
                ENTITLED_BREAKFAST,
                ENTITLED_LUNCH,
                ENTITLED_DINNER,
                DAILY_ALLOWANCE,
                //Add additional field to cater on ELAUN MAKAN for PRE-APPROVAL-REQUEST
                CURRENCY_CODE,
                ZCURRENCY.CURRENCY_DESC,
                CURRENCY_RATE,
                ////Add additional field to cater on ELAUN GALAKAN
                TYPE_OF_PROFESSIONAL_BODY,
                ZPROFESIONAL_BODY.PROFESIONAL_BODY_DESC as PROFESIONAL_BODY_DESC,
                TOTAL_TRAVELLER,
                FARE_TYPE_ID,
                ROUND_TRIP,
                INTERNAL_ORDER,
                ATTACHMENT3,
                POLICY_YEAR,
                DEPENDENT_NATIONAL_ID,
                INSURANCE_MEDICAL_PROVIDER_ID,
                INSURANCE_MEDICAL_PROVIDER_NAME,
                ZINSURANCE_MEDICAL_PROVIDER.INSURANCE_MEDICAL_PROVIDER_DESC,
                ATTACHMENT4
        };

    entity ZEMP_REQUEST_PART_VIEW         as
        projection on ECLAIM.ZREQ_ITEM_PART {
            key REQUEST_ID,
            key REQUEST_SUB_ID,
            key PARTICIPANTS_ID,
                ALLOCATED_AMOUNT,
                ZEMP_MASTER.NAME,
                ZEMP_MASTER.CC,
                createdBy
        };

    entity ZEMP_CLAIM_EE_VIEW            as
        projection on ECLAIM.ZCLAIM_HEADER {
            key CLAIM_ID,
                EMP_ID,
                COST_CENTER,
                COSTCENTER.COST_CENTER_DESC,
                ALTERNATE_COST_CENTER,
                ZCOST_CENTER.COST_CENTER_DESC as ALT_COST_CENTER_DESC,
                CLAIM_TYPE_ID,
                ZCLAIM_TYPE.CLAIM_TYPE_DESC,
                STATUS_ID,
                ZSTATUS.STATUS_DESC,
                PREAPPROVED_AMOUNT,
                ATTACHMENT_EMAIL_APPROVER,
                CASH_ADVANCE_AMOUNT,
                COMMENT,
                DIST_OLD_HOUSE_TO_NEW_HOUSE_KM,
                DIST_OLD_HOUSE_TO_OFFICE_KM,
                EVENT_END_DATE,
                EVENT_START_DATE,
                FINAL_AMOUNT_TO_RECEIVE,
                HOUSE_COMPLETION_DATE,
                HOUSING_LOAN_SCHEME,
                ZHOUSING_LOAN_SCHEME.HOUSING_LOAN_SCHEME_DESC,
                LAST_APPROVED_DATE,
                LAST_APPROVED_TIME,
                LAST_MODIFIED_DATE,
                LENDER_NAME,
                ZLENDER_NAME.LENDER_NAME as LENDER_DESC,
                LOCATION,
                MOVE_IN_DATE,
                NEW_HOUSE_ADDRESS,
                PAYMENT_DATE,
                PURPOSE,
                REQUEST_ID,
                SPECIFY_DETAILS,
                SPOUSE_OFFICE_ADDRESS,
                SUBMISSION_TYPE,
                SUBMITTED_DATE,
                TOTAL_CLAIM_AMOUNT,
                TRIP_END_DATE,
                TRIP_START_DATE,
                ZEMP_MASTER.DEP,
                ZEMP_MASTER.ZDEPARTMENT.DEPARTMENT_DESC,
                ZEMP_MASTER.NAME,
                ZEMP_MASTER.POS,
                ZEMP_MASTER.POSITION_NAME,                
                ZEMP_MASTER.GRADE,
                ZEMP_MASTER.JOB_GROUP,
                createdBy,
                modifiedAt
        };

    entity ZEMP_CLAIM_HEADER_VIEW         as
        projection on ECLAIM.ZCLAIM_HEADER {
            key CLAIM_ID,
                EMP_ID,
                COST_CENTER,
                COSTCENTER.COST_CENTER_DESC,
                ALTERNATE_COST_CENTER,
                ZCOST_CENTER.COST_CENTER_DESC  as ALT_COST_CENTER_DESC,
                CLAIM_TYPE_ID,
                ZCLAIM_TYPE.CLAIM_TYPE_DESC,
                STATUS_ID,
                ZSTATUS.STATUS_DESC,
                PREAPPROVED_AMOUNT,
                ATTACHMENT_EMAIL_APPROVER,
                CASH_ADVANCE_AMOUNT,
                COMMENT,
                DIST_OLD_HOUSE_TO_NEW_HOUSE_KM,
                DIST_OLD_HOUSE_TO_OFFICE_KM,
                EVENT_END_DATE,
                EVENT_START_DATE,
                FINAL_AMOUNT_TO_RECEIVE,
                HOUSE_COMPLETION_DATE,
                HOUSING_LOAN_SCHEME,
                ZHOUSING_LOAN_SCHEME.HOUSING_LOAN_SCHEME_DESC,
                LAST_APPROVED_DATE,
                LAST_APPROVED_TIME,
                LAST_MODIFIED_DATE,
                LENDER_NAME,
                ZLENDER_NAME.LENDER_NAME as LENDER_DESC,
                LOCATION,
                MOVE_IN_DATE,
                NEW_HOUSE_ADDRESS,
                PAYMENT_DATE,
                PURPOSE,
                REQUEST_ID,
                SPECIFY_DETAILS,
                SPOUSE_OFFICE_ADDRESS,
                SUBMISSION_TYPE,
                SUBMITTED_DATE,
                TOTAL_CLAIM_AMOUNT,
                TRIP_END_DATE,
                TRIP_START_DATE,
                ZEMP_MASTER.DEP,
                ZEMP_MASTER.ZDEPARTMENT.DEPARTMENT_DESC,
                ZEMP_MASTER.NAME,
                ZEMP_MASTER.POS,
                ZEMP_MASTER.POSITION_NAME,
                ZEMP_MASTER.GRADE,
                ZEMP_MASTER.JOB_GROUP,
                createdBy,
                modifiedAt,
                COURSE_CODE,
                ZTRAIN_COURSE_PART.COURSE_DESC as COURSE_CODE_DESC,
                SESSION_NUMBER,
                MODE_OF_TRANSFER,
                ZTRANSFER_MODE.TRANSFER_MODE_DESC,
                TRAVEL_ALONE_FAMILY,
                ZTRAVEL_TYPE.TRAVEL_TYPE_DESC,
                TRAVEL_FAMILY_NOW_LATER,
                ZFAMILY_TIMING.FAMILY_TIMING_DESC,
                PROJECT_CODE,
                ZPROJECT_HDR.PROJECT_DESC as PROJECT_DESC,
                CARD_NO,
                CCC_ADV_AMT
        };

    entity ZEMP_CLAIM_ITEM_VIEW           as
        select from ECLAIM.ZCLAIM_ITEM 
        left join ZEMP_CLAIM_POLICY_VALID as PrevPolicy
            on PrevPolicy.DEPENDENT_NATIONAL_ID = ZCLAIM_ITEM.DEPENDENT_NATIONAL_ID
            and PrevPolicy.POLICY_YEAR = ZCLAIM_ITEM.POLICY_YEAR - 1

        left join ZEMP_CLAIM_POLICY_VALID as CurrPolicy
            on CurrPolicy.DEPENDENT_NATIONAL_ID = ZCLAIM_ITEM.DEPENDENT_NATIONAL_ID
            and CurrPolicy.POLICY_YEAR = ZCLAIM_ITEM.POLICY_YEAR

        left join ZEMP_CLAIM_POLICY_VALID as NextPolicy
            on NextPolicy.DEPENDENT_NATIONAL_ID = ZCLAIM_ITEM.DEPENDENT_NATIONAL_ID
            and NextPolicy.POLICY_YEAR = ZCLAIM_ITEM.POLICY_YEAR + 1        
        {
            key ZCLAIM_ITEM.CLAIM_ID,
            key ZCLAIM_ITEM.CLAIM_SUB_ID,
                ZCLAIM_ITEM.CLAIM_TYPE_ID,
                ZCLAIM_ITEM.ZCLAIM_TYPE.CLAIM_TYPE_DESC,
                ZCLAIM_ITEM.CLAIM_TYPE_ITEM_ID,
                ZCLAIM_ITEM.ZCLAIM_TYPE_ITEM.CLAIM_TYPE_ITEM_DESC,
                ZCLAIM_ITEM.PERCENTAGE_COMPENSATION,
                ZCLAIM_ITEM.COURSE_TITLE,
                ZCLAIM_ITEM.ACCOUNT_NO,
                ZCLAIM_ITEM.AMOUNT,
                ZCLAIM_ITEM.ATTACHMENT_FILE_1,
                ZCLAIM_ITEM.ATTACHMENT_FILE_2,
                ZCLAIM_ITEM.BILL_NO,
                ZCLAIM_ITEM.BILL_DATE,
                ZCLAIM_ITEM.CLAIM_CATEGORY,
                ZCLAIM_ITEM.ZCLAIM_CATEGORY.CLAIM_CATEGORY_DESC,
                ZCLAIM_ITEM.COUNTRY,
                ZCLAIM_ITEM.ZCOUNTRY.COUNTRY_DESC,
                ZCLAIM_ITEM.DISCLAIMER,
                ZCLAIM_ITEM.START_DATE,
                ZCLAIM_ITEM.END_DATE,
                ZCLAIM_ITEM.START_TIME,
                ZCLAIM_ITEM.END_TIME,
                ZCLAIM_ITEM.FLIGHT_CLASS,
                ZCLAIM_ITEM.ZFLIGHT_CLASS.FLIGHT_CLASS_DESC,
                ZCLAIM_ITEM.FROM_LOCATION,
                ZCLAIM_ITEM.FROM_LOCATION_OFFICE,
                ZCLAIM_ITEM.KM,
                ZCLAIM_ITEM.LOCATION,
                ZCLAIM_ITEM.LOCATION_TYPE,
                ZCLAIM_ITEM.ZLOC_TYPE.LOC_TYPE_DESC,
                ZCLAIM_ITEM.LODGING_CATEGORY,
                ZCLAIM_ITEM.ZLODGING_CAT.LODGING_CATEGORY_DESC,
                ZCLAIM_ITEM.LODGING_ADDRESS,
                ZCLAIM_ITEM.MARRIAGE_CATEGORY,
                ZCLAIM_ITEM.ZMARITAL_CAT.MARRIAGE_CATEGORY_DESC,
                ZCLAIM_ITEM.AREA,
                ZCLAIM_ITEM.ZAREA.AREA_DESC,
                ZCLAIM_ITEM.NO_OF_FAMILY_MEMBER,
                ZCLAIM_ITEM.PARKING,
                ZCLAIM_ITEM.PHONE_NO,
                ZCLAIM_ITEM.RATE_PER_KM,
                ZCLAIM_ITEM.RECEIPT_DATE,
                ZCLAIM_ITEM.RECEIPT_NUMBER,
                ZCLAIM_ITEM.REMARK,
                ZCLAIM_ITEM.ROOM_TYPE,
                ZCLAIM_ITEM.ZROOM_TYPE.ROOM_TYPE_DESC,
                ZCLAIM_ITEM.REGION,
                ZCLAIM_ITEM.ZREGION.REGION_DESC,
                ZCLAIM_ITEM.FROM_STATE_ID,
                ZCLAIM_ITEM.TO_STATE_ID,
                ZCLAIM_ITEM.TO_LOCATION,
                ZCLAIM_ITEM.TO_LOCATION_OFFICE,
                ZCLAIM_ITEM.TOLL,
                ZCLAIM_ITEM.TOTAL_EXP_AMOUNT,
                ZCLAIM_ITEM.VEHICLE_TYPE,
                ZCLAIM_ITEM.ZVEHICLE_TYPE.VEHICLE_TYPE_DESC,
                ZCLAIM_ITEM.VEHICLE_FARE,
                ZCLAIM_ITEM.TRIP_START_DATE,
                ZCLAIM_ITEM.TRIP_END_DATE,
                ZCLAIM_ITEM.EVENT_START_DATE,
                ZCLAIM_ITEM.EVENT_END_DATE,
                ZCLAIM_ITEM.TRAVEL_DURATION_DAY,
                ZCLAIM_ITEM.TRAVEL_DURATION_HOUR,
                ZCLAIM_ITEM.PROVIDED_BREAKFAST,
                ZCLAIM_ITEM.PROVIDED_LUNCH,
                ZCLAIM_ITEM.PROVIDED_DINNER,
                ZCLAIM_ITEM.ENTITLED_BREAKFAST,
                ZCLAIM_ITEM.ENTITLED_LUNCH,
                ZCLAIM_ITEM.ENTITLED_DINNER,
                ZCLAIM_ITEM.ANGGOTA_ID,
                ZCLAIM_ITEM.ANGGOTA_NAME,
                ZCLAIM_ITEM.DEPENDENT_NAME,
                ZCLAIM_ITEM.TYPE_OF_PROFESSIONAL_BODY,
                ZCLAIM_ITEM.DISCLAIMER_GALAKAN,
                ZCLAIM_ITEM.VEHICLE_OWNERSHIP_ID,
                ZCLAIM_ITEM.ZVEHICLE_OWNERSHIP.VEHICLE_OWNERSHIP_DESC,
                ZCLAIM_ITEM.MODE_OF_TRANSFER,
                ZCLAIM_ITEM.TRANSFER_DATE,
                ZCLAIM_ITEM.NO_OF_DAYS,
                ZCLAIM_ITEM.FAMILY_COUNT,
                ZCLAIM_ITEM.FUNERAL_TRANSPORTATION,
                ZCLAIM_ITEM.createdBy,
                ZCLAIM_ITEM.ACTUAL_AMOUNT,
                ZCLAIM_ITEM.CURRENCY_CODE,
                ZCLAIM_ITEM.CURRENCY_RATE,
                ZCLAIM_ITEM.CURRENCY_AMOUNT,
                ZCLAIM_ITEM.FARE_TYPE_ID,
                ZCLAIM_ITEM.ZFARE_TYPE.FARE_TYPE_DESC,
                ZCLAIM_ITEM.VEHICLE_CLASS_ID,
                ZCLAIM_ITEM.ZVEHICLE_CLASS.VEHICLE_CLASS_DESC,
                ZCLAIM_ITEM.EMP_ID,
                ZCLAIM_ITEM.ZEMP_MASTER.NAME,
                ZCLAIM_ITEM.ROUND_TRIP,
                ZCLAIM_ITEM.TRIP_START_TIME,
                ZCLAIM_ITEM.TRIP_END_TIME,
                ZCLAIM_ITEM.COST_CENTER,
                ZCLAIM_ITEM.ZCOSTCENTER.COST_CENTER_DESC,
                ZCLAIM_ITEM.GL_ACCOUNT,
                ZCLAIM_ITEM.ZGL_ACCOUNT.GL_ACCOUNT_DESC,
                ZCLAIM_ITEM.MATERIAL_CODE,
                ZCLAIM_ITEM.ZMATERIAL_GROUP.MATERIAL_CODE_DESC,
                ZCLAIM_ITEM.PURPOSE,
                ZCLAIM_ITEM.MOBILE_CATEGORY_PURPOSE_ID,
                ZCLAIM_ITEM.ZMOBILE_CATEGORY_PURPOSE.MOBILE_CATEGORY_PURPOSE_DESC,
                ZCLAIM_ITEM.STUDY_LEVELS_ID,
                ZCLAIM_ITEM.ZSTUDY_LEVELS.STUDY_LEVELS_DESC,
                ZCLAIM_ITEM.NEED_FOREIGN_CURRENCY,
                ZCLAIM_ITEM.REQUEST_APPROVAL_AMOUNT,
                ZCLAIM_ITEM.DEPARTURE_TIME,
                ZCLAIM_ITEM.ARRIVAL_TIME,
                ZCLAIM_ITEM.DEPENDENT,
                ZCLAIM_ITEM.POLICY_NUMBER,
                ZCLAIM_ITEM.INSURANCE_PROVIDER_ID,
                ZCLAIM_ITEM.ZINSURANCE_PROVIDER.INSURANCE_PROVIDER_DESC,
                ZCLAIM_ITEM.ZCLAIM_HEADER.COURSE_CODE,
                ZCLAIM_ITEM.ZCLAIM_HEADER.ZTRAIN_COURSE_PART.COURSE_DESC    as COURSE_CODE_DESC,
                ZCLAIM_ITEM.ZCLAIM_HEADER.ZTRAIN_COURSE_PART.SESSION_NUMBER as SESSION_NUMBER,
                ZCLAIM_ITEM.INSURANCE_PROVIDER_NAME,
                ZCLAIM_ITEM.INSURANCE_PACKAGE_ID,
                ZCLAIM_ITEM.ZINSURANCE_PACKAGE.ZINSURANCE_PACKAGE_DESC,
                ZCLAIM_ITEM.INSURANCE_PURCHASE_DATE,
                ZCLAIM_ITEM.INSURANCE_CERT_START_DATE,
                ZCLAIM_ITEM.INSURANCE_CERT_END_DATE,
                ZCLAIM_ITEM.TRAVEL_DAYS_ID,
                ZCLAIM_ITEM.ZTRAVEL_DAYS.TRAVEL_DAYS_DESC,
                ZCLAIM_ITEM.METER_CUBE_ENTITLED,
                ZCLAIM_ITEM.METER_CUBE_ACTUAL,
                ZCLAIM_ITEM.DAILY_ALLOWANCE,
                ZCLAIM_ITEM.TIPS,
                ZCLAIM_ITEM.EXCLUDE_TIPS,
                ZCLAIM_ITEM.TOTAL_TRAVELLER,
                ZCLAIM_ITEM.ZCLAIM_HEADER.STATUS_ID,
                ZCLAIM_ITEM.ZCLAIM_HEADER.ZSTATUS.STATUS_DESC,
                ZCLAIM_ITEM.INTERNAL_ORDER,
                ZCLAIM_ITEM.COURSE_DURATION,
                ZCLAIM_ITEM.ATTACHMENT_FILE_3,
                ZCLAIM_ITEM.CHARGED_TO_CCC,
                ZCLAIM_ITEM.POLICY_YEAR,
                PrevPolicy.POLICY_NUMBER as PREVIOUS_POLICY_NUMBER,
                CurrPolicy.POLICY_NUMBER as CURRENT_POLICY_NUMBER,
                NextPolicy.POLICY_NUMBER as NEXT_POLICY_NUMBER,
                ZCLAIM_ITEM.POLICY_START_DATE,
                ZCLAIM_ITEM.POLICY_END_DATE,
                ZCLAIM_ITEM.INSURANCE_MEDICAL_PROVIDER_ID,
                ZCLAIM_ITEM.ZINSURANCE_MEDICAL_PROVIDER.INSURANCE_MEDICAL_PROVIDER_DESC,
                ZCLAIM_ITEM.INSURANCE_MEDICAL_PROVIDER_NAME,
                ZCLAIM_ITEM.ATTACHMENT_FILE_4,
                ZCLAIM_ITEM.DEPENDENT_NATIONAL_ID                     
        };

    entity ZEMP_REQUEST_STATUS            as
        projection on ECLAIM.ZREQUEST_HEADER {
            key REQUEST_ID,
                OBJECTIVE_PURPOSE,
                REQUEST_TYPE_ID,
                ZREQUEST_TYPE.REQUEST_TYPE_DESC,
                STATUS,
                ZSTATUS.STATUS_DESC,
                TRIP_START_DATE,
                EVENT_START_DATE,
                PREAPPROVAL_AMOUNT,
                TOTAL_AMOUNT,
                EMP_ID,
                createdBy
        };

    entity ZEMP_CLAIM_STATUS_HEADER       as
        projection on ECLAIM.ZCLAIM_HEADER {
            key CLAIM_ID,
                STATUS_ID,
                ZSTATUS.STATUS_DESC,
                EMP_ID,
                createdBy
        };

    entity ZEMP_CLAIM_STATUS_ITEM         as
        projection on ECLAIM.ZCLAIM_ITEM {
            key CLAIM_ID,
            key CLAIM_SUB_ID,
                START_DATE,
                AMOUNT,
                createdBy
        };

    entity ZEMP_CLAIM_REPORT_SUMMARY      as
        projection on ECLAIM.ZCLAIM_HEADER {
            key CLAIM_ID,
                EMP_ID,
                ZREQUEST_HEADER.REQUEST_ID,
                ZREQUEST_HEADER.REQUEST_DATE,
                CLAIM_TYPE_ID,
                ZCLAIM_TYPE.CLAIM_TYPE_DESC,
                ZCLAIM_TYPE.GL_ACCOUNT,
                ZEMP_MASTER.NAME,
                ZEMP_MASTER.GRADE,
                ZEMP_MASTER.DEP,
                ZEMP_MASTER.ZDEPARTMENT.DEPARTMENT_DESC,
                ZEMP_MASTER.POSITION_NAME,
                SUBMISSION_TYPE,
                ZSUBMISSION_TYPE.SUBMISSION_TYPE_DESC,
                SUBMITTED_DATE,
                ZREQUEST_HEADER.CASH_ADVANCE_DATE,
                LAST_APPROVED_DATE,
                PAYMENT_DATE,
                STATUS_ID,
                ZSTATUS.STATUS_DESC,
                COST_CENTER,
                COSTCENTER.COST_CENTER_DESC,
                ALTERNATE_COST_CENTER,
                FINAL_AMOUNT_TO_RECEIVE,
                ZCOST_CENTER.COST_CENTER_DESC as ALT_COST_CENTER_DESC,
                TOTAL_CLAIM_AMOUNT,
                CASH_ADVANCE_AMOUNT,
                PURPOSE,
                COMMENT,
                TRIP_START_DATE,
                TRIP_END_DATE,
                LOCATION,
                APPROVER1,
                APPROVER2,
                APPROVER3,
                APPROVER4,
                APPROVER5,
                ZEMP_MASTER.UNIT_SECTION,
                ZTRAIN_COURSE_PART.COURSE_ID,
                ZTRAIN_COURSE_PART.COURSE_DESC,
                ZTRAIN_COURSE_PART.SESSION_NUMBER,
                LAST_PUSH_BACK_DATE,
                createdBy
        };

    entity ZEMP_CLAIM_REPORT_DETAILS      as
        projection on ECLAIM.ZCLAIM_HEADER {
            key CLAIM_ID,
            key ZCLAIM_ITEM.CLAIM_SUB_ID,
                EMP_ID,
                ZEMP_MASTER.NAME,
                ZEMP_MASTER.GRADE,
                ZEMP_MASTER.DEP,
                ZEMP_MASTER.ZDEPARTMENT.DEPARTMENT_DESC,
                ZEMP_MASTER.POSITION_NAME,
                SUBMISSION_TYPE,
                ZSUBMISSION_TYPE.SUBMISSION_TYPE_DESC,
                SUBMITTED_DATE,
                LAST_APPROVED_DATE,
                ZREQUEST_HEADER.CASH_ADVANCE_DATE,
                PAYMENT_DATE,
                STATUS_ID,
                ZSTATUS.STATUS_DESC,
                COST_CENTER,
                COSTCENTER.COST_CENTER_DESC,
                ALTERNATE_COST_CENTER,
                ZCOST_CENTER.COST_CENTER_DESC                                as ALT_COST_CENTER_DESC,
                TOTAL_CLAIM_AMOUNT,
                CASH_ADVANCE_AMOUNT,
                FINAL_AMOUNT_TO_RECEIVE,
                PURPOSE,
                LOCATION,
                CLAIM_TYPE_ID,
                TRIP_START_DATE                                              as TRIP_START_DATE_HEADER,
                TRIP_END_DATE                                                as TRIP_END_DATE_HEADER,
                ZCLAIM_TYPE.CLAIM_TYPE_DESC,
                ZCLAIM_ITEM.CLAIM_TYPE_ITEM_ID,
                ZCLAIM_ITEM.ZCLAIM_TYPE_ITEM.CLAIM_TYPE_ITEM_DESC,
                ZCLAIM_ITEM.REMARK,
                ZCLAIM_ITEM.TRIP_START_DATE,
                ZCLAIM_ITEM.TRIP_START_TIME,
                ZCLAIM_ITEM.TRIP_END_DATE,
                ZCLAIM_ITEM.TRIP_END_TIME,
                ZCLAIM_ITEM.LOCATION                                         as LOCATION_ITEM,
                ZCLAIM_ITEM.PERCENTAGE_COMPENSATION,
                ZCLAIM_ITEM.ACCOUNT_NO,
                ZCLAIM_ITEM.AMOUNT,
                ZCLAIM_ITEM.BILL_DATE,
                ZCLAIM_ITEM.BILL_NO,
                ZCLAIM_ITEM.CLAIM_CATEGORY,
                ZCLAIM_ITEM.COUNTRY,
                ZCLAIM_ITEM.DISCLAIMER,
                ZCLAIM_ITEM.END_DATE,
                ZCLAIM_ITEM.END_TIME,
                ZCLAIM_ITEM.FLIGHT_CLASS,
                ZCLAIM_ITEM.ZFLIGHT_CLASS.FLIGHT_CLASS_DESC,
                ZCLAIM_ITEM.FROM_LOCATION,
                ZCLAIM_ITEM.FROM_LOCATION_OFFICE,
                ZCLAIM_ITEM.ZOFFICE_DISTANCE.ZOFFICE_LOCATION.LOCATION_DESC  as FROM_LOCATION_DESC,
                ZCLAIM_ITEM.KM,
                ZCLAIM_ITEM.LOCATION_TYPE,
                ZCLAIM_ITEM.ZLOC_TYPE.LOC_TYPE_DESC,
                ZCLAIM_ITEM.LODGING_ADDRESS,
                ZCLAIM_ITEM.LODGING_CATEGORY,
                ZCLAIM_ITEM.ZLODGING_CAT.LODGING_CATEGORY_DESC,
                ZCLAIM_ITEM.MARRIAGE_CATEGORY,
                ZCLAIM_ITEM.ZMARITAL_CAT.MARRIAGE_CATEGORY_DESC,
                ZCLAIM_ITEM.AREA,
                ZCLAIM_ITEM.ZAREA.AREA_DESC,
                ZCLAIM_ITEM.NO_OF_FAMILY_MEMBER,
                ZCLAIM_ITEM.PARKING,
                ZCLAIM_ITEM.PHONE_NO,
                ZCLAIM_ITEM.RATE_PER_KM,
                ZCLAIM_ITEM.RECEIPT_DATE,
                ZCLAIM_ITEM.RECEIPT_NUMBER,
                ZCLAIM_ITEM.ROOM_TYPE,
                ZCLAIM_ITEM.ZROOM_TYPE.ROOM_TYPE_DESC,
                ZCLAIM_ITEM.REGION,
                ZCLAIM_ITEM.ZREGION.REGION_DESC,
                ZCLAIM_ITEM.START_DATE,
                ZCLAIM_ITEM.START_TIME,
                ZCLAIM_ITEM.TO_LOCATION,
                ZCLAIM_ITEM.TO_LOCATION_OFFICE,
                ZCLAIM_ITEM.ZOFFICE_DISTANCE.ZOFFICE_LOCATION1.LOCATION_DESC as TO_LOCATION_DESC,
                ZCLAIM_ITEM.TOLL,
                ZCLAIM_ITEM.TOTAL_EXP_AMOUNT,
                ZCLAIM_ITEM.VEHICLE_TYPE,
                ZCLAIM_ITEM.ZVEHICLE_TYPE.VEHICLE_TYPE_DESC,
                ZCLAIM_ITEM.VEHICLE_FARE,
                ZCLAIM_ITEM.EVENT_START_DATE,
                ZCLAIM_ITEM.EVENT_END_DATE,
                ZCLAIM_ITEM.TRAVEL_DURATION_DAY,
                ZCLAIM_ITEM.TRAVEL_DURATION_HOUR,
                ZCLAIM_ITEM.PROVIDED_BREAKFAST,
                ZCLAIM_ITEM.PROVIDED_LUNCH,
                ZCLAIM_ITEM.PROVIDED_DINNER,
                ZCLAIM_ITEM.ENTITLED_BREAKFAST,
                ZCLAIM_ITEM.ENTITLED_LUNCH,
                ZCLAIM_ITEM.ENTITLED_DINNER,
                ZCLAIM_ITEM.ANGGOTA_ID,
                ZCLAIM_ITEM.ANGGOTA_NAME,
                ZCLAIM_ITEM.DEPENDENT_NAME,
                ZCLAIM_ITEM.FROM_STATE_ID,
                ZCLAIM_ITEM.ZSTATE.STATE_DESC                                as FROM_STATE_DESC,
                ZCLAIM_ITEM.TO_STATE_ID,
                ZCLAIM_ITEM.ZTOSTATE.STATE_DESC                              as TO_STATE_DESC,
                ZCLAIM_ITEM.GL_ACCOUNT,
                ZCLAIM_ITEM.MATERIAL_CODE,
                ZREQUEST_HEADER.REQUEST_ID,
                ZREQUEST_HEADER.REQUEST_DATE,
                APPROVER1,
                APPROVER2,
                APPROVER3,
                APPROVER4,
                APPROVER5,
                ZEMP_MASTER.UNIT_SECTION,
                ZTRAIN_COURSE_PART.COURSE_ID,
                ZTRAIN_COURSE_PART.COURSE_DESC,
                ZTRAIN_COURSE_PART.SESSION_NUMBER,
                LAST_PUSH_BACK_DATE,
                createdBy,
                ZCLAIM_ITEM.ROUND_TRIP,
                ZCLAIM_ITEM.TYPE_OF_PROFESSIONAL_BODY,
                ZCLAIM_ITEM.ZPROFESIONAL_BODY.PROFESIONAL_BODY_DESC,
                ZCLAIM_ITEM.DISCLAIMER_GALAKAN,
                ZCLAIM_ITEM.TRANSFER_DATE,
                ZCLAIM_ITEM.NO_OF_DAYS,
                ZCLAIM_ITEM.FAMILY_COUNT,
                ZCLAIM_ITEM.FUNERAL_TRANSPORTATION,
                ZCLAIM_ITEM.ZTRANSPORT_PASSING.TRANSPORT_PASSING_DESC,
                ZCLAIM_ITEM.COURSE_TITLE,
                ZCLAIM_ITEM.ACTUAL_AMOUNT,
                ZCLAIM_ITEM.NEED_FOREIGN_CURRENCY,
                ZCLAIM_ITEM.CURRENCY_CODE,
                ZCLAIM_ITEM.ZCURRENCY.CURRENCY_DESC,
                ZCLAIM_ITEM.CURRENCY_RATE,
                ZCLAIM_ITEM.CURRENCY_AMOUNT,
                ZCLAIM_ITEM.REQUEST_APPROVAL_AMOUNT,
                ZCLAIM_ITEM.DEPARTURE_TIME,
                ZCLAIM_ITEM.ARRIVAL_TIME,
                ZCLAIM_ITEM.DEPENDENT,
                ZCLAIM_ITEM.ZEMP_DEPENDENT.DEPENDENT_NO,
                ZCLAIM_ITEM.POLICY_NUMBER,
                ZCLAIM_ITEM.INSURANCE_PROVIDER_ID,
                ZCLAIM_ITEM.ZINSURANCE_PROVIDER.INSURANCE_PROVIDER_DESC,
                ZCLAIM_ITEM.INSURANCE_PROVIDER_NAME,
                ZCLAIM_ITEM.INSURANCE_PURCHASE_DATE,
                ZCLAIM_ITEM.INSURANCE_CERT_START_DATE,
                ZCLAIM_ITEM.INSURANCE_CERT_END_DATE,
                ZCLAIM_ITEM.TRAVEL_DAYS_ID,
                ZCLAIM_ITEM.ZTRAVEL_DAYS.TRAVEL_DAYS_DESC,
                ZCLAIM_ITEM.METER_CUBE_ENTITLED,
                ZCLAIM_ITEM.METER_CUBE_ACTUAL,
                ZCLAIM_ITEM.INSURANCE_PACKAGE_ID,
                ZCLAIM_ITEM.ZINSURANCE_PACKAGE.ZINSURANCE_PACKAGE_DESC,
                ZCLAIM_ITEM.FARE_TYPE_ID,
                ZCLAIM_ITEM.ZFARE_TYPE.FARE_TYPE_DESC,
                ZCLAIM_ITEM.VEHICLE_CLASS_ID,
                ZCLAIM_ITEM.ZVEHICLE_CLASS.VEHICLE_CLASS_DESC,
                ZCLAIM_ITEM.MOBILE_CATEGORY_PURPOSE_ID,
                ZCLAIM_ITEM.ZMOBILE_CATEGORY_PURPOSE.MOBILE_CATEGORY_PURPOSE_DESC,
                ZCLAIM_ITEM.STUDY_LEVELS_ID,
                ZCLAIM_ITEM.ZSTUDY_LEVELS.STUDY_LEVELS_DESC,
                ZCLAIM_ITEM.MODE_OF_TRANSFER,
                ZCLAIM_ITEM.ZTRANSFER_MODE.TRANSFER_MODE_DESC,
                ZCLAIM_ITEM.VEHICLE_OWNERSHIP_ID,
                ZCLAIM_ITEM.ZVEHICLE_OWNERSHIP.VEHICLE_OWNERSHIP_DESC,
        };

    entity ZEMP_REQUEST_REPORT_SUMMARY    as
        projection on ECLAIM.ZREQUEST_HEADER {
            key REQUEST_ID,
                EMP_ID,
                REQUEST_TYPE_ID,
                ZREQUEST_TYPE.REQUEST_TYPE_DESC,
                CASH_ADVANCE_DATE,
                COST_CENTER,
                ZCOST_CENTER.COST_CENTER_DESC,
                ALTERNATE_COST_CENTER,
                COSTCENTER.COST_CENTER_DESC as ALT_COST_CENTER_DESC,
                TOTAL_AMOUNT,
                CASH_ADVANCE,
                OBJECTIVE_PURPOSE,
                TRIP_START_DATE,
                TRIP_END_DATE,
                EVENT_START_DATE,
                EVENT_END_DATE,
                LOCATION,
                TYPE_OF_TRANSPORTATION,
                REMARK,
                ZEMP_MASTER.UNIT_SECTION,
                ZEMP_MASTER.ZBRANCH.BRANCH_DESC,
                REQUEST_DATE,
                STATUS,
                ZSTATUS.STATUS_DESC,
                ZEMP_MASTER.NAME,
                ZEMP_MASTER.GRADE,
                ZEMP_MASTER.DEP,
                ZEMP_MASTER.ZDEPARTMENT.DEPARTMENT_DESC,
                ZEMP_MASTER.POSITION_NAME,
                APPROVER1,
                APPROVER2,
                APPROVER3,
                APPROVER4,
                APPROVER5,
                LAST_PUSH_BACK_DATE,
                LAST_APPROVED_DATE,
                CASH_ADVANCE_DATE           as PAYMENT_DATE,
                SUBMITTED_DATE,
                CLAIM_TYPE_ID,
                ZCLAIM_TYPE.CLAIM_TYPE_DESC,
                ZCLAIM_TYPE.GL_ACCOUNT,
                createdBy
        };

    entity ZEMP_REQUEST_REPORT_DETAILS    as
        projection on ECLAIM.ZREQUEST_HEADER {
            key REQUEST_ID,
            key ZREQUEST_ITEM.REQUEST_SUB_ID,
                EMP_ID,
                REQUEST_TYPE_ID,
                ZREQUEST_TYPE.REQUEST_TYPE_DESC,
                CASH_ADVANCE_DATE,
                COST_CENTER,
                ZCOST_CENTER.COST_CENTER_DESC,
                ALTERNATE_COST_CENTER,
                COSTCENTER.COST_CENTER_DESC                                    as ALT_COST_CENTER_DESC,
                TOTAL_AMOUNT,
                CASH_ADVANCE,
                OBJECTIVE_PURPOSE,
                TRIP_START_DATE,
                TRIP_END_DATE,
                EVENT_START_DATE,
                EVENT_END_DATE,
                LOCATION,
                TYPE_OF_TRANSPORTATION,
                STATUS,
                ZSTATUS.STATUS_DESC,
                ZREQUEST_ITEM.CLAIM_TYPE_ID,
                ZREQUEST_ITEM.CLAIM_TYPE_ITEM_ID,
                ZREQUEST_ITEM.ZCLAIM_TYPE_ITEM.CLAIM_TYPE_ITEM_DESC,
                ZREQUEST_ITEM.EST_AMOUNT,
                ZREQUEST_ITEM.EST_NO_PARTICIPANT,
                REQUEST_DATE,
                ZREQUEST_ITEM.CASH_ADVANCE                                     as CASH_ADV_YES_NO,
                ZREQUEST_ITEM.START_DATE,
                ZREQUEST_ITEM.END_DATE,
                ZREQUEST_ITEM.REMARK,
                ZEMP_MASTER.UNIT_SECTION,
                ZEMP_MASTER.ZBRANCH.BRANCH_DESC,
                ZEMP_MASTER.NAME,
                ZEMP_MASTER.GRADE,
                ZEMP_MASTER.DEP,
                ZEMP_MASTER.ZDEPARTMENT.DEPARTMENT_DESC,
                ZEMP_MASTER.POSITION_NAME,
                ZREQUEST_ITEM.DECLARE_CLUB_MEMBERSHIP,
                ZREQUEST_ITEM.KWSP_SPORTS_REPRESENTATION,
                ZREQUEST_ITEM.ZSPORTS_REPRESENTATION.SPORTS_REPRESENTATION_DESC,
                ZREQUEST_ITEM.SPORTS_CLAIM_DISCLAIMER,
                ZREQUEST_ITEM.VEHICLE_OWNERSHIP_ID,
                ZREQUEST_ITEM.ZVEHICLE_OWNERSHIP.VEHICLE_OWNERSHIP_DESC,
                ZREQUEST_ITEM.MODE_OF_TRANSFER,
                ZREQUEST_ITEM.ZTRANSFER_MODE.TRANSFER_MODE_DESC,
                ZREQUEST_ITEM.TRANSFER_DATE,
                ZREQUEST_ITEM.NO_OF_DAYS,
                ZREQUEST_ITEM.MARRIAGE_CATEGORY,
                ZREQUEST_ITEM.ZMARITAL_CAT.MARRIAGE_CATEGORY_DESC,
                ZREQUEST_ITEM.FAMILY_COUNT,
                ZREQUEST_ITEM.GL_ACCOUNT,
                ZREQUEST_ITEM.MATERIAL_CODE,
                APPROVER1,
                APPROVER2,
                APPROVER3,
                APPROVER4,
                APPROVER5,
                LAST_PUSH_BACK_DATE,
                SUBMITTED_DATE,
                LAST_APPROVED_DATE,
                CASH_ADVANCE_DATE                                              as PAYMENT_DATE,
                CLAIM_TYPE_ID                                                  as CLAIM_TYPE_HEADER,
                ZCLAIM_TYPE.CLAIM_TYPE_DESC                                    as CLAIM_TYPE_DESC_HEADER,
                createdBy,
                ZREQUEST_ITEM.COURSE_TITLE,
                ZREQUEST_ITEM.KILOMETER,
                ZREQUEST_ITEM.RATE_PER_KM,
                ZREQUEST_ITEM.FLIGHT_CLASS,
                ZREQUEST_ITEM.ZFLIGHT_CLASS.FLIGHT_CLASS_DESC,
                ZREQUEST_ITEM.LOCATION_TYPE,
                ZREQUEST_ITEM.ZLOC_TYPE.LOC_TYPE_DESC,
                ZREQUEST_ITEM.COUNTRY,
                ZREQUEST_ITEM.ZCOUNTRY.COUNTRY_DESC,
                ZREQUEST_ITEM.FROM_STATE_ID,
                ZREQUEST_ITEM.ZSTATE.STATE_DESC                                as FROM_STATE_DESC,
                ZREQUEST_ITEM.TO_STATE_ID,
                ZREQUEST_ITEM.ZTOSTATE.STATE_DESC                              as TO_STATE_DESC,
                ZREQUEST_ITEM.FROM_LOCATION,
                ZREQUEST_ITEM.FROM_LOCATION_OFFICE,
                ZREQUEST_ITEM.ZOFFICE_DISTANCE.ZOFFICE_LOCATION.LOCATION_DESC  as FROM_LOCATION_DESC,
                ZREQUEST_ITEM.TO_LOCATION,
                ZREQUEST_ITEM.TO_LOCATION_OFFICE,
                ZREQUEST_ITEM.ZOFFICE_DISTANCE.ZOFFICE_LOCATION1.LOCATION_DESC as TO_LOCATION_DESC,
                ZREQUEST_ITEM.MOBILE_CATEGORY_PURPOSE_ID,
                ZREQUEST_ITEM.ZMOBILE_CATEGORY_PURPOSE.MOBILE_CATEGORY_PURPOSE_DESC,
                ZREQUEST_ITEM.TOLL,
                ZREQUEST_ITEM.VEHICLE_TYPE,
                ZREQUEST_ITEM.ZVEHICLE_TYPE.VEHICLE_TYPE_DESC,
                ZREQUEST_ITEM.REGION,
                ZREQUEST_ITEM.ZREGION.REGION_DESC,
                ZREQUEST_ITEM.ROOM_TYPE,
                ZREQUEST_ITEM.ZROOM_TYPE.ROOM_TYPE_DESC,
                ZREQUEST_ITEM.LODGING_CATEGORY,
                ZREQUEST_ITEM.ZLODGING_CAT.LODGING_CATEGORY_DESC,
                ZREQUEST_ITEM.AREA,
                ZREQUEST_ITEM.ZAREA.AREA_DESC,
                ZREQUEST_ITEM.START_TIME,
                ZREQUEST_ITEM.END_TIME,
                ZREQUEST_ITEM.DEPENDENT,
                ZREQUEST_ITEM.METER_CUBE_ENTITLED,
                ZREQUEST_ITEM.METER_CUBE_ACTUAL,
                ZREQUEST_ITEM.FARE_TYPE_ID,
                ZREQUEST_ITEM.ZFARE_TYPE.FARE_TYPE_DESC,
                ZREQUEST_ITEM.VEHICLE_CLASS_ID,
                ZREQUEST_ITEM.ZVEHICLE_CLASS.VEHICLE_CLASS_DESC,
                ZREQUEST_ITEM.PURPOSE,
                ZREQUEST_ITEM.DEPARTURE_TIME,
                ZREQUEST_ITEM.ARRIVAL_TIME,
                ZREQUEST_ITEM.TOTAL_TRAVELLER,
        };

    entity ZEMP_APPROVER_REQUEST_DETAILS  as
        projection on ECLAIM.ZAPPROVER_DETAILS_PREAPPROVAL {
            key PREAPPROVAL_ID,
            key LEVEL,
                STATUS,
                ZSTATUS.STATUS_DESC,
                APPROVER_ID,
                ZEMP_MASTER_APPROVER.NAME         as APPROVER_NAME,
                ZEMP_MASTER_APPROVER.EMAIL        as APPROVER_EMAIL,
                SUBSTITUTE_APPROVER_ID,
                ZEMP_MASTER_SUBS.NAME             as SUBSTITUTE_NAME,
                ZEMP_MASTER_SUBS.EMAIL            as SUBSTITUTE_EMAIL,
                ZREQUEST_HEADER.OBJECTIVE_PURPOSE,
                ZREQUEST_HEADER.EMP_ID,
                ZREQUEST_HEADER.REQUEST_TYPE_ID,
                ZREQUEST_HEADER.ZEMP_MASTER.NAME  as EMPLOYEE_NAME,
                ZREQUEST_HEADER.ZEMP_MASTER.EMAIL as EMPLOYEE_EMAIL,
                ZREQUEST_HEADER.REQUEST_DATE,
                ZREQUEST_HEADER.CASH_ADVANCE,
                ZREQUEST_HEADER.PREAPPROVAL_AMOUNT,
                REJECT_REASON_ID,
                ZREJECT_REASON.REASON_DESC,
                PROCESS_TIMESTAMP,
                COMMENT,
                modifiedAt
        };

    entity ZEMP_APPROVER_CLAIM_DETAILS    as
        projection on ECLAIM.ZAPPROVER_DETAILS_CLAIMS {
            key CLAIM_ID,
            key LEVEL,
                STATUS,
                ZSTATUS.STATUS_DESC,
                APPROVER_ID,
                ZEMP_MASTER_APPROVER.NAME       as APPROVER_NAME,
                ZEMP_MASTER_APPROVER.EMAIL      as APPROVER_EMAIL,
                SUBSTITUTE_APPROVER_ID,
                ZEMP_MASTER_SUBS.NAME           as SUBSTITUTE_NAME,
                ZEMP_MASTER_SUBS.EMAIL          as SUBSTITUTE_EMAIL,
                ZCLAIM_HEADER.EMP_ID,
                ZCLAIM_HEADER.ZEMP_MASTER.NAME  as EMPLOYEE_NAME,
                ZCLAIM_HEADER.ZEMP_MASTER.EMAIL as EMPLOYEE_EMAIL,
                ZCLAIM_HEADER.PURPOSE,
                ZCLAIM_HEADER.SUBMITTED_DATE,
                ZCLAIM_HEADER.FINAL_AMOUNT_TO_RECEIVE,
                ZCLAIM_HEADER.TOTAL_CLAIM_AMOUNT,
                ZCLAIM_HEADER.PREAPPROVED_AMOUNT,
                REJECT_REASON_ID,
                ZREJECT_REASON.REASON_DESC,
                PROCESS_TIMESTAMP,
                COMMENT,
                modifiedAt
        };

    entity ZEMP_CLAIM_DETAILS             as
    projection on ECLAIM.ZCLAIM_HEADER {
        key CLAIM_ID,
        key ZCLAIM_ITEM.CLAIM_SUB_ID,
            EMP_ID,
            LAST_MODIFIED_DATE,
            SUBMITTED_DATE,
            FINAL_AMOUNT_TO_RECEIVE,
            ZCLAIM_ITEM.RECEIPT_DATE,
            ZCLAIM_ITEM.AMOUNT,
            ZCLAIM_ITEM.COST_CENTER,
            ZCLAIM_ITEM.GL_ACCOUNT,
            ZCLAIM_ITEM.MATERIAL_CODE,
            CASH_ADVANCE_AMOUNT,
            ALTERNATE_COST_CENTER,
            ZCLAIM_ITEM.INTERNAL_ORDER,
            ZCLAIM_TYPE.CASH_ADVANCE_CAT_ID,
            ZCLAIM_ITEM.CHARGED_TO_CCC,
            ZCLAIM_ITEM.CLAIM_TYPE_ITEM_ID,
            CARD_NO,
            CLAIM_TYPE_ID
    };

    entity ZEMP_PREAPPROVAL_DETAILS       as
        projection on ECLAIM.ZREQUEST_HEADER {
            key REQUEST_ID,
            key ZREQUEST_ITEM.REQUEST_SUB_ID,
                EMP_ID,
                modifiedAt                 as LAST_MODIFIED_DATE,
                SUBMITTED_DATE,
                CASH_ADVANCE,
                ZREQUEST_ITEM.CASH_ADVANCE as CASH_ADVANCE_ITEM,
                ZREQUEST_ITEM.EST_AMOUNT,
                ZREQUEST_ITEM.COST_CENTER,
                ZREQUEST_ITEM.GL_ACCOUNT,
                TRIP_START_DATE,
                STATUS,
                //Previously, the view returned records across all statuses, including those already sent to SF.
                // With the addition of these fields, the view now filters only approved records that have not yet been sent to SF.
                ZSTATUS.STATUS_DESC,
                ZREQUEST_ITEM.SEND_TO_SF,
                ZCLAIM_TYPE.CASH_ADVANCE_CAT_ID
        }

        where
                ZSTATUS.STATUS_ID          =  'STAT05'
            and ZREQUEST_ITEM.CASH_ADVANCE =  true
            and ZREQUEST_ITEM.SEND_TO_SF   is null;


    @cds.redirection.target
    entity ZEMP_CLAIM_BUDGET_CHECK        as
        projection on ECLAIM.ZCLAIM_HEADER {
            key CLAIM_ID,
            key ZCLAIM_ITEM.CLAIM_SUB_ID,
                SUBMITTED_DATE,
                COST_CENTER,
                ALTERNATE_COST_CENTER,
                ZCLAIM_ITEM.AMOUNT,
                ZCLAIM_ITEM.GL_ACCOUNT,
                ZCLAIM_ITEM.MATERIAL_CODE,
                createdBy
        };

    entity ZEMP_REQUEST_BUDGET_CHECK      as
        projection on ECLAIM.ZREQUEST_HEADER {
            key REQUEST_ID,
            key ZREQUEST_ITEM.REQUEST_SUB_ID,
                REQUEST_DATE,
                COST_CENTER,
                ALTERNATE_COST_CENTER,
                ZREQUEST_ITEM.EST_AMOUNT,
                ZREQUEST_ITEM.GL_ACCOUNT,
                ZREQUEST_ITEM.MATERIAL_CODE,
                createdBy
        };

    entity ZEMP_APPROVER_DETAILS  as
            select from ECLAIM.ZAPPROVER_DETAILS_PREAPPROVAL as request {
                key PREAPPROVAL_ID                     as ID,
                key LEVEL,
                    STATUS,
                    ZSTATUS.STATUS_DESC                as STATUS_DESC,
                    ZREQUEST_HEADER.OBJECTIVE_PURPOSE  as PURPOSE,
                    APPROVER_ID,
                    ZEMP_MASTER_APPROVER.NAME          as APPROVER_NAME,
                    ZEMP_MASTER_APPROVER.EMAIL         as APPROVER_EMAIL,
                    ZREQUEST_HEADER.REQUEST_DATE       as REQUEST_DATE,
                    ZREQUEST_HEADER.PREAPPROVAL_AMOUNT as AMOUNT,
                    ZREQUEST_HEADER.CASH_ADVANCE       as TOTAL_AMOUNT,
                    modifiedAt,
                    SUBSTITUTE_APPROVER_ID,
                    ZEMP_MASTER_SUBS.NAME             as SUBSTITUTE_NAME
            }
            where
                ZSTATUS.STATUS_DESC = 'PENDING APPROVAL'
        union all
            select from ECLAIM.ZAPPROVER_DETAILS_CLAIMS as claim {
                key CLAIM_ID                              as ID,
                key LEVEL,
                    STATUS,
                    ZSTATUS.STATUS_DESC                   as STATUS_DESC,
                    ZCLAIM_HEADER.PURPOSE                 as PURPOSE,
                    APPROVER_ID,
                    ZEMP_MASTER_APPROVER.NAME             as APPROVER_NAME,
                    ZEMP_MASTER_APPROVER.EMAIL            as APPROVER_EMAIL,
                    ZCLAIM_HEADER.SUBMITTED_DATE          as REQUEST_DATE,
                    ZCLAIM_HEADER.FINAL_AMOUNT_TO_RECEIVE as AMOUNT,
                    ZCLAIM_HEADER.TOTAL_CLAIM_AMOUNT      as TOTAL_AMOUNT,
                    modifiedAt,
                    SUBSTITUTE_APPROVER_ID,
                    ZEMP_MASTER_SUBS.NAME             as SUBSTITUTE_NAME
            }
            where
                ZSTATUS.STATUS_DESC = 'PENDING APPROVAL';

    action sendApprovedClaimBatch(batch: ApprovedClaimBatch) returns {
        message : String;
    };

    entity ZROLEHIERARCHY                as
        projection on ECLAIM.ZROLEHIERARCHY {
            key ROLE,
                RANK
        };

    entity ZCONSTANTS                    as
        projection on ECLAIM.ZCONSTANTS {
            key ID,
                VALUE
        };

    entity ZCLM_APPR_REQ_STAT_VIEW        as
        projection on ECLAIM.ZCLM_APPR_REQ_STAT {
            key EMP_ID,
            key REQUEST_ID,
                AMOUNT,
                CLAIMED,
                ZREQUEST_HEADER : Association to one ECLAIM_VIEW_SRV.ZEMP_REQUEST_VIEW
                                      on ZREQUEST_HEADER.REQUEST_ID = REQUEST_ID
        };

    entity ZEMP_SUBSTITUTION_RULE         as projection on ECLAIM.ZSUBSTITUTION_RULES;

    entity ZCLM_OFFICE_LOCATION_SELECTION as
        select from ECLAIM.ZOFFICE_DISTANCE {
            key FROM_STATE_ID,
                ZSTATE.STATE_DESC               as FROM_STATE_DESC,
            key FROM_LOCATION_ID,
                ZOFFICE_LOCATION.LOCATION_DESC  as FROM_LOCATION_DESC,
            key TO_STATE_ID,
                ZTOSTATE.STATE_DESC             as TO_STATE_DESC,
            key TO_LOCATION_ID,
                ZOFFICE_LOCATION1.LOCATION_DESC as TO_LOCATION_DESC,
                STATUS
        }
        group by
            FROM_STATE_ID,
            ZSTATE.STATE_DESC,
            FROM_LOCATION_ID,
            ZOFFICE_LOCATION.LOCATION_DESC,
            TO_STATE_ID,
            ZTOSTATE.STATE_DESC,
            TO_LOCATION_ID,
            ZOFFICE_LOCATION1.LOCATION_DESC,
            STATUS;

    entity ZCLM_TO_STATE_SELECTION        as
        select from ECLAIM.ZOFFICE_DISTANCE {
            key FROM_STATE_ID,
                ZSTATE.STATE_DESC              as FROM_STATE_DESC,
            key FROM_LOCATION_ID,
                ZOFFICE_LOCATION.LOCATION_DESC as FROM_LOCATION_DESC,
            key TO_STATE_ID,
                ZTOSTATE.STATE_DESC            as TO_STATE_DESC,
                STATUS
        }
        group by
            FROM_STATE_ID,
            ZSTATE.STATE_DESC,
            FROM_LOCATION_ID,
            ZOFFICE_LOCATION.LOCATION_DESC,
            TO_STATE_ID,
            ZTOSTATE.STATE_DESC,
            STATUS;

    entity ZCLM_COURSE_VIEW               as
        projection on ECLAIM.ZTRAIN_COURSE_PART {
            key COURSE_ID || '|' || SESSION_NUMBER || '|' || cast(
                    START_DATE as String
                ) || '|' || cast(
                    END_DATE as String
                ) as COURSE_SESSION_KEY : String,
                COURSE_ID,
                PARTICIPANT_ID,
                COURSE_DESC,
                COURSE_SESSION_STAT,
                ATTENDENCE_STATUS,
        }
        group by
            COURSE_ID,
            PARTICIPANT_ID,
            COURSE_DESC,
            COURSE_SESSION_STAT,
            ATTENDENCE_STATUS,
            SESSION_NUMBER,
            START_DATE,
            END_DATE;

    entity ZEMP_ACCESS               as
        projection on ECLAIM.ZEMP_MASTER {
            key EEID,
                NAME, 
                POS,
                JOB_GROUP,
                GRADE,
                GA_ROLE,
                ECLAIM_ROLE
        };

    entity ZPROJECT_DROPDOWN_VH as
        select from ECLAIM.ZBUDGET {
            key YEAR,
            key PROJECT_CODE,
                ZPROJECT_HDR.PROJECT_DESC as PROJECT_DESC,
                ZPROJECT_HDR.STATUS       as STATUS
        }
            where PROJECT_CODE is not null
            and PROJECT_CODE <> ''
            and PROJECT_CODE <> '-';

    entity ZPARTICIPANT_PREAPPROVED_AMOUNT as
        select from ECLAIM.ZREQ_ITEM_PART as itemPart
            inner join ECLAIM.ZREQUEST_HEADER as req
                on itemPart.REQUEST_ID = req.REQUEST_ID
        {
            key itemPart.REQUEST_ID,
            key itemPart.PARTICIPANTS_ID,

            req.EMP_ID,
            req.CLAIM_TYPE_ID,
            req.STATUS,
            
            req.OBJECTIVE_PURPOSE,
            req.TRIP_START_DATE,
            req.TRIP_END_DATE,
            req.EVENT_START_DATE,
            req.EVENT_END_DATE,

            req.ALTERNATE_COST_CENTER,
            req.PREAPPROVAL_AMOUNT as HEADER_PREAPPROVAL_AMOUNT,
            req.CASH_ADVANCE,
            req.PROJECT_CODE,

            req.TRANSFER_MODE_ID,
            req.TRAVEL_ALONE_FAMILY,
            req.TRAVEL_FAMILY_NOW_LATER,

            sum(itemPart.ALLOCATED_AMOUNT) as PREAPPROVED_AMOUNT : Decimal
        }
        where
            req.STATUS = 'STAT05'
            
        group by
            itemPart.REQUEST_ID,
            itemPart.PARTICIPANTS_ID,
            
            req.EMP_ID,
            req.CLAIM_TYPE_ID,
            req.STATUS,

            req.OBJECTIVE_PURPOSE,
            req.TRIP_START_DATE,
            req.TRIP_END_DATE,
            req.EVENT_START_DATE,
            req.EVENT_END_DATE,

            req.ALTERNATE_COST_CENTER,
            req.PREAPPROVAL_AMOUNT,
            req.CASH_ADVANCE,
            req.PROJECT_CODE,

            req.TRANSFER_MODE_ID,
            req.TRAVEL_ALONE_FAMILY,
            req.TRAVEL_FAMILY_NOW_LATER;

    entity ZEMP_CLAIM_POLICY_VALID as
        select from ECLAIM.ZCLAIM_ITEM as item
            inner join ECLAIM.ZCLAIM_HEADER as header
                on header.CLAIM_ID = item.CLAIM_ID
    {
        key item.CLAIM_SUB_ID,
            item.CLAIM_ID,
            header.STATUS_ID,
            POLICY_NUMBER,
            POLICY_YEAR,
            DEPENDENT_NATIONAL_ID
    }
    where header.STATUS_ID in ('STAT02', 'STAT05', 'STAT06');           
}